Repository CultureConnect2024/CultureConnect-MD, pull requests merged in 2024-12, with the labels that each got.

#23 [PULL REQUEST] restyle home bookmark
  .idea/dbnavigator.xml
  .idea/deploymentTargetDropDown.xml
  .idea/git_toolbox_prj.xml
  app/src/main/java/app/culturedev/cultureconnect/ui/MainActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: develop

#24 Restyle home bookmark
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeFragment.kt
  app/src/main/res/layout/activity_mood_result.xml
  app/src/main/res/values/strings.xml
Labels: develop

#27 update main and favorite activity
  app/build.gradle.kts
  app/src/main/java/app/culturedev/cultureconnect/data/di/Injection.kt
  app/src/main/java/app/culturedev/cultureconnect/data/model/UserModel.kt
  app/src/main/java/app/culturedev/cultureconnect/data/preferences/UserPreferences.kt
  app/src/main/java/app/culturedev/cultureconnect/data/remote/api/ApiService.kt
  app/src/main/java/app/culturedev/cultureconnect/data/repository/CafeRepo.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/DataRes.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/ErrorRes.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/LoginRes.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/RegisterRes.kt
  app/src/main/java/app/culturedev/cultureconnect/data/result/ResultCafe.kt
  app/src/main/java/app/culturedev/cultureconnect/helper/Utils.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/Adapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/detail/DetailViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/favorite/FavoriteViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/maps/MapsFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/DetailViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/FavoriteViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/LoginViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/MainViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/MapsViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/RegisterViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/FactoryViewModel.kt
  app/src/main/res/drawable/baseline_filter_alt_24.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_maps.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: develop

#31 [PULL REQUEST] Added firebase check if user was loginned
  app/src/main/java/app/culturedev/cultureconnect/ui/auth/register/RegisterActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/DescribeMoodActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/MainViewModel.kt
  app/src/main/res/layout/activity_describe_mood.xml
  app/src/main/res/layout/activity_mood_result.xml
  gradle/libs.versions.toml
Labels: develop

#36 [PULL REQUEST] Handle no connection exception
  app/src/main/java/app/culturedev/cultureconnect/helper/NetworkUtil.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/auth/login/LoginActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/auth/register/RegisterActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/detail/DetailActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/favorite/FavoriteFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/CafeResultActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/DescribeMoodActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/MoodResultActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/settings/SettingsFragment.kt
Labels: develop

#37 [PULL REQUEST] Added Viewmodel factory (Without DI LIBS)
  app/src/main/java/app/culturedev/cultureconnect/data/di/Injection.kt
  app/src/main/java/app/culturedev/cultureconnect/data/preferences/UserPreferences.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/DetailViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/FavoriteViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/MapsViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/FactoryViewModel.kt
Labels: develop

#39 33 reworked onboarding screen
  .idea/render.experimental.xml
  app/src/main/java/app/culturedev/cultureconnect/ui/auth/login/LoginActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/settings/SettingsFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/splash/WelcomeActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/splash/onboarding/FirstScreenFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/splash/onboarding/SecondScreenFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/splash/onboarding/ThirdScreenFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/splash/onboarding/ViewPagerFragment.kt
  app/src/main/res/drawable/onboarding_page_one.png
  app/src/main/res/drawable/onboarding_page_two.png
  app/src/main/res/layout/activity_cafe_result.xml
  app/src/main/res/layout/activity_describe_mood.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/fragment_first_screen.xml
  app/src/main/res/layout/fragment_second_screen.xml
  app/src/main/res/layout/fragment_third_screen.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: develop

#44 43 intent stack bug
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/settings/SettingsFragment.kt
  app/src/main/res/navigation/navigation.xml
Labels: bug

#46 Google maps integration
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/culturedev/cultureconnect/ui/maps/MapsFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/splash/onboarding/FirstScreenFragment.kt
  app/src/main/res/layout/fragment_maps.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: develop

#48 Reworked layout of user profile
  app/src/main/res/layout/fragment_settings.xml
Labels: styling

#50 Fetch current user data
  app/src/main/java/app/culturedev/cultureconnect/helper/Utils.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/maps/MapsFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/settings/SettingsFragment.kt
Labels: develop

#53 Added recomender system
  app/src/main/java/app/culturedev/cultureconnect/data/di/Injection.kt
  app/src/main/java/app/culturedev/cultureconnect/data/remote/api/ApiConfig.kt
  app/src/main/java/app/culturedev/cultureconnect/data/remote/api/RecommendationApiService.kt
  app/src/main/java/app/culturedev/cultureconnect/data/repository/RecommendationRepository.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/recommendation/RecommendationRequest.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/recommendation/RecommendationResponse.kt
  app/src/main/java/app/culturedev/cultureconnect/helper/Utils.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/RecommenderAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/CafeResultActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/DescribeMoodActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/MoodResultActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/DescribeMoodViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/FactoryViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/RecommendationFactoryViewModel.kt
  app/src/main/res/layout/activity_describe_mood.xml
  app/src/main/res/layout/list_item.xml
Labels: develop

#54 Display detail of recommended cafe
  app/src/main/java/app/culturedev/cultureconnect/helper/Utils.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/RecommenderAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/detail/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/list_item.xml
Labels: develop

#57 feat: send user category data
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/RecommenderAdapter.kt
Labels: develop

#58 Implement recomendation system
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/culturedev/cultureconnect/data/remote/api/ApiConfig.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/recommendation/RecommendationResponse.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/RecommenderAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/CafeResultActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/DescribeMoodActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/MoodResultActivity.kt
  app/src/main/res/drawable/angry.jpeg
  app/src/main/res/drawable/fear.jpeg
  app/src/main/res/drawable/joy.jpeg
  app/src/main/res/drawable/love.jpeg
  app/src/main/res/drawable/sad.jpeg
  app/src/main/res/drawable/surprise.jpeg
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/xml/network_security_config.xml
Labels: develop

#60 Fetch list of cafe from API
  app/src/main/java/app/culturedev/cultureconnect/data/di/Injection.kt
  app/src/main/java/app/culturedev/cultureconnect/data/remote/api/RecommendationApiService.kt
  app/src/main/java/app/culturedev/cultureconnect/data/repository/RecommendationRepository.kt
  app/src/main/java/app/culturedev/cultureconnect/data/response/listcafe/ListCafeResponse.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/ListCafeAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/DetailViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/FactoryViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/RecommendationFactoryViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: develop

#63 40 cafe notification screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/culturedev/cultureconnect/data/database/AppDatabase.kt
  app/src/main/java/app/culturedev/cultureconnect/data/database/Dao.kt
  app/src/main/java/app/culturedev/cultureconnect/data/database/DataEntity.kt
  app/src/main/java/app/culturedev/cultureconnect/data/database/FavoriteDao.kt
  app/src/main/java/app/culturedev/cultureconnect/data/database/FavoriteData.kt
  app/src/main/java/app/culturedev/cultureconnect/data/database/HistoryDao.kt
  app/src/main/java/app/culturedev/cultureconnect/data/database/HistoryData.kt
  app/src/main/java/app/culturedev/cultureconnect/data/di/Injection.kt
  app/src/main/java/app/culturedev/cultureconnect/data/remote/api/ApiService.kt
  app/src/main/java/app/culturedev/cultureconnect/data/repository/RecommendationRepository.kt
  app/src/main/java/app/culturedev/cultureconnect/helper/Utils.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/Adapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/FavoriteAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/FavoriteAndHistoryAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/ListCafeAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/adapter/RecommenderAdapter.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/allCafe/AllCafeActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/auth/login/LoginActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/auth/register/RegisterActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/detail/DetailActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/favorite/FavoriteFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/history/HistoryActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeFragment.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/recomendation/CafeResultActivity.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/AllCafeViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/DetailViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/FavoriteViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/HistoryViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/SharedViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/FactoryViewModel.kt
  app/src/main/java/app/culturedev/cultureconnect/ui/viewmodel/factory/RecommendationFactoryViewModel.kt
  app/src/main/res/drawable/baseline_bookmark_border_24.xml
  app/src/main/res/layout/activity_all_cafe.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/values/style.xml
Labels: develop

#64 Check if user was login
  app/build.gradle.kts
  app/src/main/java/app/culturedev/cultureconnect/ui/home/HomeFragment.kt
Labels: bugfix

#66 Rregister form validation with Rxjava 2
  app/build.gradle.kts
  app/src/main/java/app/culturedev/cultureconnect/ui/auth/register/RegisterActivity.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: develop
